### ISSUE TITLE
Don't let Rock Margin take over the whole bar area.

### ISSUE THREAD

**Issue by KCarterSr** [ArkEcho/RockMargin#2]
Here is the screenshot you requested. It's just a screen shot of what I currently have.

Hope this helps.

Cheers

![image](https://github.com/ArkEcho/RockMargin/assets/2046991/9bf36bb8-7e83-43bc-9fd4-ef7931b0edc9)

**Comment by ArkEcho** [comment]
Hi @KCarterSr,

I don't have access to other Extensions Marks nor can I provide any support for the thousands of VS Add-Ins. You either have to uninstall the Extension or fix the Issue yourself - by creating a Pull Request.

To quote the Description: "This is released with exactly **zero warranty or support**. If it deletes files or kills your family pet, you have been warned. It might work great, and it might not. **It hasn't been tested against the myriad of other VS Add-Ins**, but it works well on my machine."
